In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os


In [8]:
#1. scalar

tf.constant(1)
tf.rank(tf.constant([1]))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
print('vector')
tf.rank(tf.constant([1,2,3]))


vector


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [27]:
# Create a scalar
a = tf.constant(5)

# Create a row vector
b = tf.constant([1, 2])

# Create a 2x3 matrix
c = tf.constant([[1,2],
                 [4, 5]])
# C_matrix = tf.constant([[1,2],
#                         [1,2]])

# Create a 3x3x3 tensor
d = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],
                 [[10,11,12],[13,14,15],[16,17,18]],
                 [[19,20,21],[22,23,24],[25,26,27]]])

In [15]:
#2 find shape rank size
print('scalar')
print(tf.shape(a))
print(tf.rank(a))
print(tf.size(a))
print(a.ndim)

scalar
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
0


In [16]:
print('vector')
print(tf.shape(b))
print(tf.rank(b))
print(tf.size(b))
print(b.ndim)

vector
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
1


In [19]:
print('matrix')
print(tf.shape(c))
print(tf.rank(c))
print(tf.size(c))
print(c.ndim)

matrix
tf.Tensor([2 3 1], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
3


In [20]:
tf.constant([[2,3],[1,3],[4,5]]).ndim

2

In [21]:
print('tensor')
print(tf.shape(d))
print(tf.rank(d))
print(tf.size(d))
print(d.ndim)

tensor
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(27, shape=(), dtype=int32)
3


In [28]:
def shapeRankSize(name,i):
    print(name)
    print(tf.shape(i))
    print(tf.rank(i))
    print(tf.size(i))
    print(i.ndim)

shapeRankSize('scalar',a)
shapeRankSize('vector',b)
shapeRankSize('matrix',c)
shapeRankSize('tensor',d)

scalar
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
0
vector
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
1
matrix
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
2
tensor
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(27, shape=(), dtype=int32)
3


In [37]:
# 3.
random_a = tf.random.uniform(shape=[5,300], minval=0, maxval=1)
random_b = tf.random.uniform(shape=[5,300], minval=0, maxval=1)



In [30]:
#4. matrix multiplication
print('matrix multiplication')
print(tf.matmul(random_a,tf.transpose(random_b)))

matrix multiplication
tf.Tensor(
[[79.15422  80.07552  82.78888  79.706696 80.49078 ]
 [70.55159  76.344765 72.4666   72.055374 74.06755 ]
 [70.62576  71.46511  72.783875 74.03499  72.75073 ]
 [72.218994 74.11778  76.942215 75.69386  72.34317 ]
 [73.06435  77.84204  75.68373  74.750694 74.7875  ]], shape=(5, 5), dtype=float32)


In [33]:
#5. dot product
print('dot product')
print(tf.tensordot(random_a,tf.transpose(random_b),axes=1))

dot product
tf.Tensor(
[[79.15422  80.07552  82.78888  79.706696 80.49078 ]
 [70.55159  76.344765 72.4666   72.055374 74.06755 ]
 [70.62576  71.46511  72.783875 74.03499  72.75073 ]
 [72.218994 74.11778  76.942215 75.69386  72.34317 ]
 [73.06435  77.84204  75.68373  74.750694 74.7875  ]], shape=(5, 5), dtype=float32)


In [36]:
#6. random
print('random')
random_c = tf.random.uniform(shape=[224,224,3], minval=0, maxval=1)


random


In [35]:
random_b

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5684215 , 0.0414027 , 0.46036983],
        [0.13045597, 0.05508399, 0.15724134],
        [0.7907293 , 0.77445304, 0.10803139],
        ...,
        [0.16297221, 0.30038893, 0.8130729 ],
        [0.19176471, 0.644577  , 0.2719202 ],
        [0.95632136, 0.13209355, 0.15459883]],

       [[0.32721806, 0.865283  , 0.49055052],
        [0.2725327 , 0.5800886 , 0.96008897],
        [0.9184823 , 0.4497701 , 0.55526924],
        ...,
        [0.9588499 , 0.8424953 , 0.97935176],
        [0.5827732 , 0.07882321, 0.91778517],
        [0.37766957, 0.1075238 , 0.26397455]],

       [[0.64076805, 0.6201974 , 0.97780573],
        [0.42302752, 0.9604932 , 0.50878954],
        [0.16134071, 0.8011068 , 0.26929748],
        ...,
        [0.06748581, 0.15849173, 0.52232695],
        [0.6073512 , 0.98726285, 0.8784766 ],
        [0.7147387 , 0.83001006, 0.04322493]],

       ...,

       [[0.8099425 , 0.85828316, 0.14818895],
        [0.08

In [43]:
min_val = tf.reduce_min(random_b).numpy()
max_val = tf.reduce_max(random_b).numpy()

print(min_val)
print(max_val)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

9.775162e-06
0.9987345
Minimum value: 9.775162e-06
Maximum value: 0.9987345


In [46]:
#8
random_d = tf.random.uniform(shape=[1,224,224,3], minval=0, maxval=1)
squeeze_random_d = tf.squeeze(random_d)
squeeze_random_d.shape

TensorShape([224, 224, 3])

In [51]:
#9
random_5 = tf.random.uniform([10],0,10)
print(random_5)
print("index {} has the maximum value".format(tf.argmax(random_5).numpy()))


tf.Tensor(
[5.425044  3.3633137 8.855714  6.7816353 8.70617   0.5780554 7.632048
 3.3284044 9.301047  8.206862 ], shape=(10,), dtype=float32)
index 8 has the maximum value


In [52]:
tf.one_hot(tf.cast(random_5.numpy().tolist(),tf.int32),depth=tf.size(random_5).numpy(),on_value="|",off_value="-")


<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'-', b'-', b'-', b'-', b'-', b'|', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'|', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|', b'-'],
       [b'|', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|', b'-', b'-'],
       [b'-', b'-', b'-', b'|', b'-', b'-', b'-', b'-', b'-', b'-'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|'],
       [b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'-', b'|', b'-']],
      dtype=object)>