In [1]:
import tensorflow as tf

In [2]:
print('TensorFlow version:', tf.__version__)

TensorFlow version: 2.10.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255., x_test/255.

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
])

In [5]:
predictions = model(x_train[:1])
predictions

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[0.05314458, 0.68917465, 0.38759345, 0.3398741 , 0.        ,
        0.02418573, 0.        , 0.        , 0.2099407 , 0.        ,
        0.        , 0.        , 0.2296301 , 0.        , 0.        ,
        0.        , 0.17238823, 0.        , 0.47063464, 0.42308915,
        0.73274124, 0.        , 0.        , 0.09577098, 0.        ,
        0.        , 0.21492784, 0.        , 0.        , 0.        ,
        0.3739341 , 0.        , 0.        , 0.10882267, 0.        ,
        0.34674084, 0.824277  , 0.        , 0.        , 0.60109985,
        0.6523718 , 0.        , 0.12963444, 0.2416519 , 0.        ,
        0.29383427, 0.        , 0.        , 0.20839134, 0.2782356 ,
        0.1678686 , 0.        , 0.6582246 , 0.2500834 , 0.        ,
        0.        , 0.        , 0.6658542 , 0.87821496, 0.        ,
        0.        , 0.1348195 , 0.        , 0.31320617, 0.        ,
        0.        , 0.36764517, 0.09008781, 0.        , 0.        

In [21]:
predictions.numpy()

array([[4.44940627e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 7.07779884e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.03831005e+00, 7.93327615e-02, 0.00000000e+00, 1.93926960e-01,
        0.00000000e+00, 9.52370986e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.71272850e-01, 1.26098454e+00, 0.00000000e+00,
        0.00000000e+00, 3.00452888e-01, 0.00000000e+00, 1.94931984e-01,
        8.00812662e-01, 0.00000000e+00, 1.33031929e+00, 0.00000000e+00,
        1.61024049e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.70777494e-01, 6.01931989e-01, 1.36787184e-02, 1.43826008e-04,
        3.68978947e-01, 0.00000000e+00, 0.00000000e+00, 4.64309603e-02,
        5.59853196e-01, 1.48980469e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.17765367e-01, 0.00000000e+00, 2.19233677e-01,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.000000

In [23]:
tf.nn.softmax(predictions).numpy()

array([[0.00654367, 0.0062589 , 0.0062589 , 0.0062589 , 0.0062589 ,
        0.01270231, 0.0062589 , 0.0062589 , 0.0062589 , 0.0062589 ,
        0.0062589 , 0.0062589 , 0.01767788, 0.00677566, 0.0062589 ,
        0.00759835, 0.0062589 , 0.00688429, 0.0062589 , 0.0062589 ,
        0.0062589 , 0.0110815 , 0.02208699, 0.0062589 , 0.0062589 ,
        0.00845246, 0.0062589 , 0.00760599, 0.01394076, 0.0062589 ,
        0.02367273, 0.0062589 , 0.00735241, 0.0062589 , 0.0062589 ,
        0.0062589 , 0.00820531, 0.01142651, 0.0063451 , 0.0062598 ,
        0.00905198, 0.0062589 , 0.0062589 , 0.00655636, 0.01095567,
        0.00726439, 0.0062589 , 0.0062589 , 0.0062589 , 0.00704114,
        0.0062589 , 0.00779309, 0.0062589 , 0.0062589 , 0.0062589 ,
        0.0062589 , 0.00837223, 0.0062589 , 0.0062589 , 0.00763502,
        0.00696258, 0.0062589 , 0.0062589 , 0.0062589 , 0.0062589 ,
        0.00789219, 0.00713434, 0.0062589 , 0.0070674 , 0.0104615 ,
        0.0062589 , 0.0062589 , 0.0062589 , 0.00

In [24]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [25]:
loss_fn(y_train[:1], predictions).numpy()

4.365971

In [26]:
model.compile(optimizer='Adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [27]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-04-09 22:09:22.387072: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1875/1875 [==============================] - 1s 472us/step - loss: 1.9318 - accuracy: 0.6408
Epoch 2/5
1875/1875 [==============================] - 1s 459us/step - loss: 1.7226 - accuracy: 0.6726
Epoch 3/5
1875/1875 [==============================] - 1s 453us/step - loss: 1.7099 - accuracy: 0.6751
Epoch 4/5
1875/1875 [==============================] - 1s 447us/step - loss: 1.7027 - accuracy: 0.6779
Epoch 5/5
1875/1875 [==============================] - 1s 451us/step - loss: 1.6947 - accuracy: 0.6798


In [28]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.9231 - accuracy: 0.8346 - 184ms/epoch - 588us/step


[0.9230806827545166, 0.8345999717712402]

In [32]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [31]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 128), dtype=float32, numpy=
array([[5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 1.4065658e-03,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 9.2385793e-01,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04,
        5.9313810e-04, 5.9313810e-04, 5.9313810e-04, 5.9313810e-04